In [2]:
import pandas as pd

In [46]:
RelationInstances = pd.read_parquet("tests/unit/fixtures/test_transformer/RelationInstances.parquet")

In [47]:
RelationInstances

,R1Instance,R1InstanceID,RelationInstanceID,R2Instance,R2InstanceID,R2Element,Cardinality,R1Element
0,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,0615a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,0415a391-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,Eis
1,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,1115a391-7f6e-ee11-b6a1-001dd8d702bc,Niet behandeld,a18bc184-6bd5-ea11-a2f0-00155d641104,Geaccepteerd door ON,0:1|1,Eis
2,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,164973f8-149f-ee11-b6a6-001dd8d702bf,B-AB500,a6508da9-7f6e-ee11-b6a1-001dd8d702bc,Eis,0:n,Eis
3,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,21688d68-a42c-ef11-b6ae-001dd8d702bf,Overeengekomen OG/ON,128bae1b-10d6-ea11-a2f0-00155d641104,SRA status,0:1,Eis
4,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,2315a391-7f6e-ee11-b6a1-001dd8d702bc,Wie doet wat,1f15a391-7f6e-ee11-b6a1-001dd8d702bc,WieDoetWat,0:n,Eis
5,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,25de6afe-149f-ee11-b6a6-001dd8d702bf,AB200,5adf5bd3-7f6e-ee11-b6a1-001dd8d702bc,Eis,0:n,Eis
6,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,41766704-159f-ee11-b6a6-001dd8d702bf,B-AB300,1ed53ef1-7f6e-ee11-b6a1-001dd8d702bc,Eis,0:n,Eis
7,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,6559790b-ab7f-ee11-b6a5-001dd8d702bf,Contractmanager,5aa573e8-e961-ee11-b6a0-001dd8d702bf,Rol,0:n,Eis
8,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,77be6fc2-34ce-ee11-b6a8-001dd8d702bf,ME-Eis-Bedrijfsproces,63be6fc2-34ce-ee11-b6a8-001dd8d702bf,ME-Eis-Bedrijfsproces,0:n,Eis
9,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,80756704-159f-ee11-b6a6-001dd8d702bf,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,Eis,0:n,Eis
10,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,80f442b2-0498-ee11-b6a5-001dd8d702bf,Gezamenlijke toelichting ON,76f442b2-0498-ee11-b6a5-001dd8d702bf,Gezamenlijke toelichting ON,0:n,Eis
11,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,a130b6ce-f94f-f011-b6c2-001dd8d702bc,Commentaar,9530b6ce-f94f-f011-b6c2-001dd8d702bc,Commentaar,0:n,Eis
12,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,a34773f8-149f-ee11-b6a6-001dd8d702bf,AB230,e8bd9b97-7f6e-ee11-b6a1-001dd8d702bc,Eis,0:n,Eis
13,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,b58d9db2-9b92-ee11-b6a5-001dd8d702bf,Managementeis(en),f8dd1a5e-636e-ee11-b6a1-001dd8d702bc,Type,0:1,Eis
14,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,bca73545-17e5-ee11-b6aa-001dd8d702bf,Ja,0e8bae1b-10d6-ea11-a2f0-00155d641104,SMART-analyse,0:1,Eis
15,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,d04873f8-149f-ee11-b6a6-001dd8d702bf,AB210,ce4d8da9-7f6e-ee11-b6a1-001dd8d702bc,Eis,0:n,Eis
16,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,d5dc6afe-149f-ee11-b6a6-001dd8d702bf,AB400,189c79bb-7f6e-ee11-b6a1-001dd8d702bc,Eis,0:n,Eis
17,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,dfc0ca92-edf0-ee11-b6aa-001dd8d702bf,Actueel,df657c58-70d5-ea11-a2f0-00155d641104,Status,0:1|1,Eis
18,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,ef14a391-7f6e-ee11-b6a1-001dd8d702bc,Eis tekst,eb14a391-7f6e-ee11-b6a1-001dd8d702bc,Eistekst,1:n,Eis
19,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,f914a391-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,f114a391-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,Eis
20,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,fe14a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,fc14a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,Eis
21,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,03e4fcfd-d3cc-ee11-b6a8-001dd8d702bf,Ja,0e8bae1b-10d6-ea11-a2f0-00155d641104,SMART-analyse,0:1,Eis
22,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,1bee48e5-7f6e-ee11-b6a1-001dd8d702bc,Eis tekst,17ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Eistekst,1:n,Eis
23,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,1ea5aae5-34ce-ee11-b6a8-001dd8d702bf,ME-Eis-Bedrijfsproces,0aa5aae5-34ce-ee11-b6a8-001dd8d702bf,ME-Eis-Bedrijfsproces,0:n,Eis
24,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,26ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1dee48e5-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,Eis
25,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,2aee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,28ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,Eis
26,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,33ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,31ee48e5-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,Eis
27,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,39ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Niet behandeld,a18bc184-6bd5-ea11-a2f0-00155d641104,Geaccepteerd door ON,0:1|1,Eis
28,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,3dee48e5-7f6e-ee11-b6a1-001dd8d702bc,Actueel,df657c58-70d5-ea11-a2f0-00155d641104,Status,0:1|1,Eis
29,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,42dd6afe-149f-ee11-b6a6-001dd8d702bf,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,Eis,0:n,Eis
30,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,5bb255e2-9c92-ee11-b6a5-001dd8d702bf,Managementeis(en),f8dd1a5e-636e-ee11-b6a1-001dd8d702bc,Type,0:1,Eis
31,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,69ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Wie doet wat,61ee48e5-7f6e-ee11-b6a1-001dd8d702bc,WieDoetWat,0:n,Eis
32,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,71698d68-a42c-ef11-b6ae-001dd8d702bf,Overeengekomen OG/ON,128bae1b-10d6-ea11-a2f0-00155d641104,SRA status,0:1,Eis
33,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,774773f8-149f-ee11-b6a6-001dd8d702bf,AB420,fbbb9b97-7f6e-ee11-b6a1-001dd8d702bc,Eis,0:n,Eis
34,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,cd819e17-ab7f-ee11-b6a5-001dd8d702bf,Contractmanager,5aa573e8-e961-ee11-b6a0-001dd8d702bf,Rol,0:n,Eis
35,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,267c5ffb-9f92-ee11-b6a5-001dd8d702bf,Managementeis(en),f8dd1a5e-636e-ee11-b6a1-001dd8d702bc,Type,0:1,Eis
36,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,35829e17-ab7f-ee11-b6a5-001dd8d702bf,Contractmanager,5aa573e8-e961-ee11-b6a0-001dd8d702bf,Rol,0:n,Eis
37,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,9e5869c7-7f6e-ee11-b6a1-001dd8d702bc,Eis tekst,875869c7-7f6e-ee11-b6a1-001dd8d702bc,Eistekst,1:n,Eis
38,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,a917866e-a42c-ef11-b6ae-001dd8d702bf,Overeengekomen OG/ON,128bae1b-10d6-ea11-a2f0-00155d641104,SRA status,0:1,Eis
39,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,ab5869c7-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,a25869c7-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,Eis
40,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,af5869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,ad5869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,Eis
41,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,b57c7811-35ce-ee11-b6a8-001dd8d702bf,ME-Eis-Bedrijfsproces,a17c7811-35ce-ee11-b6a8-001dd8d702bf,ME-Eis-Bedrijfsproces,0:n,Eis
42,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,b85869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,b65869c7-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,Eis
43,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,b8be1610-d4cc-ee11-b6a8-001dd8d702bf,Ja,0e8bae1b-10d6-ea11-a2f0-00155d641104,SMART-analyse,0:1,Eis
44,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,be5869c7-7f6e-ee11-b6a1-001dd8d702bc,Niet behandeld,a18bc184-6bd5-ea11-a2f0-00155d641104,Geaccepteerd door ON,0:1|1,Eis
45,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,c15869c7-7f6e-ee11-b6a1-001dd8d702bc,Actueel,df657c58-70d5-ea11-a2f0-00155d641104,Status,0:1|1,Eis
46,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,d75869c7-7f6e-ee11-b6a1-001dd8d702bc,Wie doet wat,d35869c7-7f6e-ee11-b6a1-001dd8d702bc,WieDoetWat,0:n,Eis
47,AB200,5adf5bd3-7f6e-ee11-b6a1-001dd8d702bc,1cde6afe-149f-ee11-b6a6-001dd8d702bf,AB220,f4de5bd3-7f6e-ee11-b6a1-001dd8d702bc,Eis,0:n,Eis
48,AB200,5adf5bd3-7f6e-ee11-b6a1-001dd8d702bc,2a7c5ffb-9f92-ee11-b6a5-001dd8d702bf,Managementeis(en),f8dd1a5e-636e-ee11-b6a1-001dd8d702bc,Type,0:1,Eis
49,AB200,5adf5bd3-7f6e-ee11-b6a1-001dd8d702bc,56829e17-ab7f-ee11-b6a5-001dd8d702bf,Contractmanager,5aa573e8-e961-ee11-b6a0-001dd8d702bf,Rol,0:n,Eis

In [29]:
Relations = pd.read_parquet("tests/unit/fixtures/test_transformer/Relations.parquet")

In [30]:
Relations.iloc[25:35,:]

,Relation,Cardinality,RelationID,R2Element,R2ElementID
25,Heeft betrekking op SBS Type,0:n,b121dda7-77c1-ec11-b689-001dd8d702bf,ME-Eis-SBS type,5371c67e-77c1-ec11-b689-001dd8d702bf
26,Heeft contactpersoon,0:1,79a4f66f-efa6-e911-a2df-00155d641103,Rol,48e2234a-9b2e-e911-a2d5-00155d641103
27,Heeft eigenaar,0:n,d8af7d26-f931-e911-a2d5-00155d641103,Rol,48e2234a-9b2e-e911-a2d5-00155d641103
28,Heeft property,0:1,108e6382-9747-f011-b6c2-001dd8d702bc,SRA Thema,fe4a0331-9547-f011-b6c2-001dd8d702bc
29,Heeft property,0:1,25e40114-69d5-ea11-a2f0-00155d641104,SMART-analyse,9dc8ef06-69d5-ea11-a2f0-00155d641104
30,Heeft property,0:1,44b531ee-9aae-ec11-b688-001dd8d702bf,Type,fa7e60d4-9aae-ec11-b688-001dd8d702bf
31,Heeft property,0:1,458f8a61-75f5-e911-a2e5-00155d641104,Geldig tot en met,2ecb4ecc-d1f4-e911-a2e5-00155d641104
32,Heeft property,0:1,488f8a61-75f5-e911-a2e5-00155d641104,Geldig vanaf,8f4ecdda-d1f4-e911-a2e5-00155d641104
33,Heeft property,0:1,8b045c3a-75f5-e911-a2e5-00155d641104,RI&E opvolging,34ac2ae8-d1f4-e911-a2e5-00155d641104
34,Heeft property,0:1,a68e3dcd-f092-eb11-b674-001dd8d702bc,EMVI kans,93790c78-f092-eb11-b674-001dd8d702bc